#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/TC/Documents/College/Junior/Sem2/PLT/AHOD

rm -f ast.cmi
rm -f parse.cmi
rm -f parse.cmo
rm -f parse.ml
rm -f parse.mli
rm -f scanner.cmi
rm -f scanner.cmo
rm -f scanner.ml
# Also clean the script itself
rm -f /mnt/c/Users/TC/Documents/College/Junior/Sem2/PLT/AHOD/_build/sanitize.sh
